from __future__ import annotations

import json
from typing import Any

from chunkhound.autodoc.markdown_utils import (
    _ensure_overview_heading,
    _escape_yaml,
    _strip_markdown_for_search,
)
from chunkhound.autodoc.models import (
    CodeMapperIndex,
    DocsitePage,
    DocsiteSite,
    GlossaryTerm,
    NavGroup,
)
from chunkhound.autodoc.references import strip_references_section
from chunkhound.autodoc.site_writer_metadata import _render_index_metadata
from chunkhound.autodoc.template_loader import load_bytes, load_text
from chunkhound.utils.text import safe_scope_label


def _render_favicon_bytes() -> bytes:
    return load_bytes("public/favicon.ico")


def _render_font_bytes(filename: str) -> bytes:
    return load_bytes(f"public/fonts/{filename}")


def _render_font_license_text(filename: str) -> str:
    return load_text(f"public/fonts/licenses/{filename}")


def _render_package_json(site: DocsiteSite) -> str:
    safe_name = safe_scope_label(site.scope_label).replace("_", "-")
    package_name = f"chunkhound-docs-{safe_name}" if safe_name else "chunkhound-docs"
    return load_text("package.json").replace("{{PACKAGE_NAME}}", package_name)


def _render_astro_config() -> str:
    return load_text("astro.config.mjs")


def _render_tsconfig() -> str:
    return load_text("tsconfig.json")


def _render_readme(site: DocsiteSite) -> str:
    return load_text("README.md").replace("{{TITLE}}", site.title)


def _render_site_json(site: DocsiteSite) -> str:
    payload = {
        "title": site.title,
        "tagline": site.tagline,
        "scopeLabel": site.scope_label,
        "generatedAt": site.generated_at,
        "sourceDir": site.source_dir,
        "topicCount": site.topic_count,
        "watermark": "Generated by ChunkHound",
    }
    return json.dumps(payload, ensure_ascii=True, indent=2) + "\n"


def _render_search_index(pages: list[DocsitePage]) -> str:
    records: list[dict[str, str]] = []
    for page in pages:
        body = strip_references_section(page.body_markdown)
        body_text = _strip_markdown_for_search(body)
        records.append(
            {
                "title": page.title,
                "slug": page.slug,
                "description": page.description,
                "body": body_text,
                "url": f"/topics/{page.slug}/",
            }
        )
    return json.dumps(records, ensure_ascii=True, indent=2)


def _render_nav_json(groups: list[NavGroup]) -> str:
    payload: dict[str, Any] = {"groups": [{"title": group.title, "slugs": group.slugs} for group in groups]}
    return json.dumps(payload, ensure_ascii=True, indent=2)


def _render_glossary_page(terms: list[GlossaryTerm]) -> str:
    body_lines: list[str] = [
        "This page defines canonical terms used throughout the documentation.",
        "",
    ]
    for entry in terms:
        term = entry.term.strip()
        definition = entry.definition.strip()
        pages = entry.pages
        if not term or not definition:
            continue
        body_lines.append(f"## {term}")
        body_lines.append("")
        body_lines.append(definition)
        body_lines.append("")
        if pages:
            links = ", ".join([f"[{slug}](/topics/{slug}/)" for slug in pages])
            body_lines.append(f"- Pages: {links}")
            body_lines.append("")
    body = "\n".join(body_lines).strip() + "\n"
    return _render_page_frontmatter(
        layout="../layouts/DocLayout.astro",
        title="Glossary",
        description="Definitions of common terms used across the docs.",
        order=None,
        body=body,
        source_path=None,
        scope_label=None,
        references_count=None,
    )


def _render_doc_layout() -> str:
    return load_text("src/layouts/DocLayout.astro")


def _render_global_css() -> str:
    return load_text("src/styles/global.css")


def _render_index_page(
    *,
    site: DocsiteSite,
    pages: list[DocsitePage],
    index: CodeMapperIndex,
    overview_markdown: str | None = None,
) -> str:
    body_parts: list[str] = ["Welcome to the generated AutoDoc documentation site.", ""]

    if overview_markdown and overview_markdown.strip():
        body_parts.append(_ensure_overview_heading(overview_markdown.strip()))
        body_parts.append("")

    body_parts.append("## Topics")
    body_parts.append("")

    ordered_pages = sorted(
        pages,
        key=lambda page: (page.order if page.order is not None else 9999, page.title),
    )
    for idx, page in enumerate(ordered_pages, start=1):
        body_parts.append(f"{idx}. [{page.title}](topics/{page.slug}/)")

    metadata_lines = _render_index_metadata(index)
    if metadata_lines:
        body_parts.extend(
            [
                "",
                '<details class="generation-details">',
                "<summary>Generation Details</summary>",
                "",
                *metadata_lines,
                "",
                "</details>",
            ]
        )

    body = "\n".join(body_parts).strip() + "\n"
    return _render_page_frontmatter(
        layout="../layouts/DocLayout.astro",
        title=site.title,
        description=site.tagline,
        order=None,
        body=body,
    )


def _render_topic_page(page: DocsitePage) -> str:
    return _render_page_frontmatter(
        layout="../../layouts/DocLayout.astro",
        title=page.title,
        description=page.description,
        order=page.order,
        body=page.body_markdown.strip() + "\n",
        source_path=page.source_path,
        scope_label=page.scope_label,
        references_count=page.references_count,
    )


def _render_page_frontmatter(
    *,
    layout: str,
    title: str,
    description: str,
    order: int | None,
    body: str,
    source_path: str | None = None,
    scope_label: str | None = None,
    references_count: int | None = None,
) -> str:
    def _posixify_path(value: str) -> str:
        return value.replace("\\", "/")

    lines = [
        "---",
        f"layout: {layout}",
        f'title: "{_escape_yaml(title)}"',
        f'description: "{_escape_yaml(description)}"',
    ]
    if order is not None:
        lines.append(f"order: {order}")
    if source_path:
        lines.append(f'sourcePath: "{_escape_yaml(_posixify_path(source_path))}"')
    if scope_label:
        lines.append(f'scope: "{_escape_yaml(scope_label)}"')
    if references_count is not None:
        lines.append(f"referencesCount: {references_count}")
    lines.append("---")
    lines.append("")
    lines.append(body.rstrip())
    lines.append("")
    return "\n".join(lines)
